//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Calificacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUMNOS()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
            this.NOTAS = new HashSet<NOTAS>();
        }
    
        public int ID_ALUMN { get; set; }
        public Nullable<int> ID_REPR { get; set; }
        public string NOMBRE_ALUMN { get; set; }
        public string APELLIDO_ALUMN { get; set; }
        public string CEDULA_ALUMN { get; set; }
        public string PASS_ALUMN { get; set; }
        public string DIRECCION_ALUMN { get; set; }
        public System.DateTime FECHA_NACIMINETO_ALUMN { get; set; }
    
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS> NOTAS { get; set; }
    }
}
