//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Calificacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTAS
    {
        public int ID_NOTA { get; set; }
        public Nullable<int> ID_ALUMN { get; set; }
        public Nullable<int> ID_PERIODO { get; set; }
        public Nullable<int> ID_MATER { get; set; }
        public decimal NOTA { get; set; }
        public System.DateTime FECH_HORA_REG { get; set; }
    
        public virtual ALUMNOS ALUMNOS { get; set; }
        public virtual PERIODOS_NOTAS PERIODOS_NOTAS { get; set; }
    }
}
